# Array Creation Routines

In [2]:
import numpy as np

## Ones and Zeros

Create a new array of 2*2 integers, without initializing entries.

In [3]:
np.zeros((2, 2), dtype=int)

array([[0, 0],
       [0, 0]])

Let X = np.array([[1,2,3], [4,5,6], np.int32]). Create a new array with the same shape and type as X.

In [4]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [5]:
np.eye(3)

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

Create a new array of 3*2 float numbers, filled with ones.

In [6]:
np.ones((3, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [7]:
np.ones_like(np.arange(4, dtype=np.int64))

array([1, 1, 1, 1], dtype=int64)

Create a new array of 3*2 float numbers, filled with zeros.

In [8]:
np.zeros((3, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [9]:
np.zeros_like(np.arange(4, dtype=np.int64))

array([0, 0, 0, 0], dtype=int64)