# Array Creation Routines
## Ones and Zeros
import numpy as np
Create a new array of 2*2 integers, without initializing entries.

In [1]:
np.zeros((2, 2), dtype=int)

array([[0, 0],
       [0, 0]])

Let X = np.array([[1,2,3], [4,5,6], np.int32]). Create a new array with the same shape and type as X.

In [2]:
X = np.array([[1,2,3], [4,5,6]], np.int32)

array([[1, 2, 3],
       [4, 5, 6]],
      dtype=int32)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [3]:
np.eye(3)

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

Create a new array of 3*2 float numbers, filled with ones.

In [4]:
np.ones((3, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [5]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

Create a new array of 3*2 float numbers, filled with zeros.

In [6]:
np.zeros((3, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [7]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

In [8]:
np.full((2, 5), 6, dtype=np.uint32)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]],
      dtype=uint32)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [9]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)