# Random Sampling

In [1]:
import numpy as np

# Q1
print("Q1.")
print(np.random.rand(3, 2))

Q1.
[[0.33213409 0.9939325 ]
 [0.84767777 0.2523325 ]
 [0.69274885 0.39505164]]


In [2]:
# Q2
print("\nQ2.")
data = np.random.randn(1000, 1000)
print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))

Q2.
Mean: -0.0011388746195216555
Standard Deviation: 1.000000975988446


In [3]:
# Q3
print("\nQ3.")
print(np.random.randint(0, 4, size=(3, 2)))

Q3.
[[0 2]
 [0 2]
 [1 3]]


In [4]:
# Q4
print("\nQ4.")
x = np.array([b'3 out of 10', b'5 out of 10', b'2 out of 10'])
for _ in range(10):
    print(np.random.choice(x, p=[0.3, 0.5, 0.2]))

Q4.
5 out of 10
3 out of 10
2 out of 10
5 out of 10
3 out of 10
2 out of 10
5 out of 10
2 out of 10
3 out of 10
5 out of 10


In [5]:
# Q5
print("\nQ5.")
print(np.random.choice(np.arange(10), size=3))

Q5.
[3 2 3]


In [6]:
# Q6
print("\nQ6.")
print(np.random.permutation(10))

Q6.
[3 2 0 7 9 5 6 4 1 8]


In [7]:
# Q7
print("\nQ7.")
np.random.seed(10)  # Set seed to 10
print(np.random.rand(3))

Q7.
[0.77132064 0.02075195 0.63364823]
