# Random Sampling

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [1]:
import numpy as np

print("Q1.")
print(np.random.rand(3, 2))

[[0.33213409 0.9939325 ]
 [0.84767777 0.2523325 ]
 [0.69274885 0.39505164]]


Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation are close enough to 0 and 1 respectively.

In [2]:
print("\nQ2.")
data = np.random.randn(1000, 1000)
print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))

Mean: -0.0011388746195216555
Standard Deviation: 1.000000975988446


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [3]:
print("\nQ3.")
print(np.random.randint(0, 4, size=(3, 2)))

[[0 2]
 [0 2]
 [1 3]]


Q4. Extract 1 element from x randomly such that each of them would be associated with probabilities 0.3, 0.5, 0.2. Then print the result 10 times.

x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

In [4]:
print("\nQ4.")
x = np.array([b'3 out of 10', b'5 out of 10', b'2 out of 10'])
for _ in range(10):
    print(np.random.choice(x, p=[0.3, 0.5, 0.2]))

5 out of 10
3 out of 10
5 out of 10
2 out of 10
2 out of 10
3 out of 10
2 out of 10
3 out of 10
3 out of 10
5 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [5]:
print("\nQ5.")
print(np.random.choice(np.arange(10), size=3))

[3 2 3]


Q6. Shuffle numbers between 0 and 9 (inclusive).

In [6]:
print("\nQ6.")
print(np.random.permutation(10))

[3 2 0 7 9 5 6 4 1 8]


Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [7]:
np.random.seed(10)  # Set seed to 10
print("\nQ7.")
print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]
