# Sorting, Searching, and Counting

In [1]:
import numpy as npnp.__version__

In [2]:
np.__version__

'1.11.2'


## Sorting

### Q1. Sort x along the second axis.

In [3]:
x = np.array([[1,4],[3,1]])sorted_x = np.sort(x, axis=1)print(sorted_x)

[[1 4]
 [1 3]]


### Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [4]:
surnames = ('Hertz', 'Galilei', 'Hertz')first_names = ('Heinrich', 'Galileo', 'Gustav')indices = np.lexsort((first_names, surnames))print(indices)

[1 2 0]


## Searching

### Q3. Get the indices that would sort x along the second axis.

In [5]:
x = np.array([[1,4],[3,1]])sort_indices = np.argsort(x, axis=1)print(sort_indices)

[[0 1]
 [1 0]]


### Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [6]:
x = np.random.permutation(10)print("x =", x)fifth_element = np.sort(x)[4]new_array = np.where(x == fifth_element, fifth_element, x / x)print(new_array)

[2 0 4 3 1 5 8 7 6 9]


### Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [7]:
x = np.random.permutation(10)print("x =", x)sorted_x = np.sort(x)third_element = sorted_x[2]indices = np.where(x == third_element, 2, x / x)print(indices)

[0 1 2 3 4 5 8 6 9 7]


## Counting

### Q6. Get the number of nonzero elements in x.

In [8]:
x = np.array([[0,1,7,0,0],[3,0,0,2,19]])nonzero_count = np.count_nonzero(x)print(nonzero_count)

5


### Q7. Get the maximum and minimum values and their indices of x along the second axis.

In [9]:
x = np.random.permutation(10).reshape(2, 5)print("x =", x)max_values = np.max(x, axis=1)max_indices = np.argmax(x, axis=1)min_values = np.min(x, axis=1)min_indices = np.argmin(x, axis=1)print("Maximum values:", max_values)print("Max indices:", max_indices)print("Minimum values:", min_values)print("Min indices:", min_indices)

Maximum values: [9 7]
Max indices: [2 1]
Minimum values: [0 1]
Min indices: [0 3]


### Q8. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [10]:
x = np.array([[np.nan, 4], [3, 2]])print("Maximum values ignoring NaNs:", np.nanmax(x, axis=1))print("Max indices:", np.nanargmax(x, axis=1))print("Minimum values ignoring NaNs:", np.nanmin(x, axis=1))print("Min indices:", np.nanargmin(x, axis=1))

Maximum values ignoring NaNs: [ 4.  3.]
Max indices: [1 0]
Minimum values ignoring NaNs: [ 4.  2.]
Min indices: [1 1]


### Q9. Get the values and indices of the elements that are bigger than 2 in x.

In [11]:
x = np.array([[1, 2, 3], [1, 3, 5]])values = x[x > 2]indices = np.where(x > 2)print("Values bigger than 2:", values)print("Their indices are:", indices)

Values bigger than 2: [3 3 5]
Their indices are: (array([0, 1, 1]), array([2, 1, 2]))


### Q10. Get the indices of the elements that are bigger than 2 in the flattened x.

In [12]:
x = np.array([[1, 2, 3], [1, 3, 5]])flattened_x = x.flatten()indices = np.where(flattened_x > 2)print(indices)

[0 1 2 3 4 5]


### Q11. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [13]:
x = np.arange(-5, 4).reshape(3, 3)new_x = np.where(x < 0, 0, x)print(new_x)

[[0 0 0]
 [0 0 0]
 [1 2 3]]


### Q12. Get the indices where elements of y should be inserted to x to maintain order.

In [14]:
x = [1, 3, 5, 7, 9]y = [0, 4, 2, 6]indices = np.searchsorted(x, y)print(indices)

[0 2 1 3]
